CELERY_FORCE_ROOT: "True"

global:
  NEWS_DISCOVERY_SERVICE_ELASTIC_APM__SECRET_TOKEN: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
  NEWS_DISCOVERY_ELASTIC_APM__URL: http://apm-server:8200

  NEWS_DISCOVERY_LOGSTASH__HOST: logstash
  NEWS_DISCOVERY_LOGSTASH__PORT: 5000

  NEWS_DISCOVERY_RABBIT__HOST: rabbitmq
  NEWS_DISCOVERY_RABBIT__PORT: 5672
  NEWS_DISCOVERY_RABBIT__PASSWORD: guest
  NEWS_DISCOVERY_RABBIT__USER: guest

  NEWS_DISCOVERY_CELERY__CONCURRENCY: 12