apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: news-discovery-abc
  name: news-discovery-abc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: news-discovery-abc
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: news-discovery-abc
        spec:
          containers:
            - name: news-discovery-abc
              image: 'djrevok/news-discovery-app:{{ .Chart.AppVersion }}'
              imagePullPolicy: ""
              command:
                - make
                - run_news_discovery
                - SOURCE_NAME=ABC
              envFrom:
                - configMapRef:
                    name: news-discovery-configmap
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: news-discovery-politico
  name: news-discovery-politico
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: news-discovery-politico
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: news-discovery-politico
        spec:
          containers:
            - name: news-discovery-politico
              image: 'djrevok/news-discovery-app:{{ .Chart.AppVersion }}'
              imagePullPolicy: ""
              command:
                - make
                - run_news_discovery
                - SOURCE_NAME=Politico
              envFrom:
                - configMapRef:
                    name: news-discovery-configmap
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: news-discovery-el-confidencial
  name: news-discovery-el-confidencial
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: news-discovery-el-confidencial
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: news-discovery-el-confidencial
        spec:
          containers:
            - name: news-discovery-el-confidencial
              image: 'djrevok/news-discovery-app:{{ .Chart.AppVersion }}'
              imagePullPolicy: ""
              command:
                - make
                - run_news_discovery
                - SOURCE_NAME="\"El Confidencial\""
              envFrom:
                - configMapRef:
                    name: news-discovery-configmap
          restartPolicy: OnFailure
---