apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: news-discovery-app
  name: news-discovery-app
spec:
  containers:
  - envFrom:
      - configMapRef:
          name: news-discovery-configmap
    image: djrevok/news-discovery-app:latest
    livenessProbe:
      exec:
        command:
        - celery -b amqp://guest:guest@rabbitmq:5672 inspect ping -d celery@$HOSTNAME
      failureThreshold: 10
      periodSeconds: 2
      timeoutSeconds: 20
    name: news-discovery-app
    resources: {}
  restartPolicy: OnFailure
status: {}
