apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: news-discovery-beat
  name: news-discovery-beat
spec:
  containers:
  - envFrom:
      - configMapRef:
          name: news-discovery-configmap
    image: djrevok/news-discovery-beat:latest
    name: news-discovery-beat
    resources: {}
  restartPolicy: OnFailure
status: {}
