elastic_apm:
  secret_token: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
  url: http://localhost:8200
logstash:
  host: localhost
  port: 5000
rabbit:
  host: localhost
  port: 5672
  user: guest
  password: guest
celery:
  concurrency: 12